enabled_news: ["en"]
home:
  home_link: "http://www.railstutorial.org/"
about:
  about_link: "http://www.railstutorial.org/"
help:
  help_link: "http://www.railstutorial.org/help"
contact:
  contact_link: "http://www.railstutorial.org/contact"
